/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserAdminRouteImport } from './routes/user-admin'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EditUserRouteImport } from './routes/edit-user'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as CheckoutRouteRouteImport } from './routes/checkout.route'
import { Route as CartRouteRouteImport } from './routes/cart.route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as EditUserIdRouteImport } from './routes/edit-user.$id'
import { ServerRoute as ApiProductsServerRouteImport } from './routes/api/products'
import { ServerRoute as ApiDebugProductsServerRouteImport } from './routes/api/debug-products'
import { ServerRoute as ApiCreateOrderServerRouteImport } from './routes/api.create-order'

const rootServerRouteImport = createServerRootRoute()

const UserAdminRoute = UserAdminRouteImport.update({
  id: '/user-admin',
  path: '/user-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EditUserRoute = EditUserRouteImport.update({
  id: '/edit-user',
  path: '/edit-user',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRouteRoute = CheckoutRouteRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRouteRoute = CartRouteRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EditUserIdRoute = EditUserIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EditUserRoute,
} as any)
const ApiProductsServerRoute = ApiProductsServerRouteImport.update({
  id: '/api/products',
  path: '/api/products',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiDebugProductsServerRoute = ApiDebugProductsServerRouteImport.update({
  id: '/api/debug-products',
  path: '/api/debug-products',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiCreateOrderServerRoute = ApiCreateOrderServerRouteImport.update({
  id: '/api/create-order',
  path: '/api/create-order',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRouteRoute
  '/checkout': typeof CheckoutRouteRoute
  '/categories': typeof CategoriesRoute
  '/edit-user': typeof EditUserRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/user-admin': typeof UserAdminRoute
  '/edit-user/$id': typeof EditUserIdRoute
  '/product/$id': typeof ProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRouteRoute
  '/checkout': typeof CheckoutRouteRoute
  '/categories': typeof CategoriesRoute
  '/edit-user': typeof EditUserRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/user-admin': typeof UserAdminRoute
  '/edit-user/$id': typeof EditUserIdRoute
  '/product/$id': typeof ProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRouteRoute
  '/checkout': typeof CheckoutRouteRoute
  '/categories': typeof CategoriesRoute
  '/edit-user': typeof EditUserRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/user-admin': typeof UserAdminRoute
  '/edit-user/$id': typeof EditUserIdRoute
  '/product/$id': typeof ProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/checkout'
    | '/categories'
    | '/edit-user'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/search'
    | '/user-admin'
    | '/edit-user/$id'
    | '/product/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/checkout'
    | '/categories'
    | '/edit-user'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/search'
    | '/user-admin'
    | '/edit-user/$id'
    | '/product/$id'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/checkout'
    | '/categories'
    | '/edit-user'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/search'
    | '/user-admin'
    | '/edit-user/$id'
    | '/product/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRouteRoute: typeof CartRouteRoute
  CheckoutRouteRoute: typeof CheckoutRouteRoute
  CategoriesRoute: typeof CategoriesRoute
  EditUserRoute: typeof EditUserRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  UserAdminRoute: typeof UserAdminRoute
  ProductIdRoute: typeof ProductIdRoute
}
export interface FileServerRoutesByFullPath {
  '/api/create-order': typeof ApiCreateOrderServerRoute
  '/api/debug-products': typeof ApiDebugProductsServerRoute
  '/api/products': typeof ApiProductsServerRoute
}
export interface FileServerRoutesByTo {
  '/api/create-order': typeof ApiCreateOrderServerRoute
  '/api/debug-products': typeof ApiDebugProductsServerRoute
  '/api/products': typeof ApiProductsServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/create-order': typeof ApiCreateOrderServerRoute
  '/api/debug-products': typeof ApiDebugProductsServerRoute
  '/api/products': typeof ApiProductsServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/api/create-order' | '/api/debug-products' | '/api/products'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/api/create-order' | '/api/debug-products' | '/api/products'
  id: '__root__' | '/api/create-order' | '/api/debug-products' | '/api/products'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiCreateOrderServerRoute: typeof ApiCreateOrderServerRoute
  ApiDebugProductsServerRoute: typeof ApiDebugProductsServerRoute
  ApiProductsServerRoute: typeof ApiProductsServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user-admin': {
      id: '/user-admin'
      path: '/user-admin'
      fullPath: '/user-admin'
      preLoaderRoute: typeof UserAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit-user': {
      id: '/edit-user'
      path: '/edit-user'
      fullPath: '/edit-user'
      preLoaderRoute: typeof EditUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit-user/$id': {
      id: '/edit-user/$id'
      path: '/$id'
      fullPath: '/edit-user/$id'
      preLoaderRoute: typeof EditUserIdRouteImport
      parentRoute: typeof EditUserRoute
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/products': {
      id: '/api/products'
      path: '/api/products'
      fullPath: '/api/products'
      preLoaderRoute: typeof ApiProductsServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/debug-products': {
      id: '/api/debug-products'
      path: '/api/debug-products'
      fullPath: '/api/debug-products'
      preLoaderRoute: typeof ApiDebugProductsServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/create-order': {
      id: '/api/create-order'
      path: '/api/create-order'
      fullPath: '/api/create-order'
      preLoaderRoute: typeof ApiCreateOrderServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

interface EditUserRouteChildren {
  EditUserIdRoute: typeof EditUserIdRoute
}

const EditUserRouteChildren: EditUserRouteChildren = {
  EditUserIdRoute: EditUserIdRoute,
}

const EditUserRouteWithChildren = EditUserRoute._addFileChildren(
  EditUserRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRouteRoute: CartRouteRoute,
  CheckoutRouteRoute: CheckoutRouteRoute,
  CategoriesRoute: CategoriesRoute,
  EditUserRoute: EditUserRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  UserAdminRoute: UserAdminRoute,
  ProductIdRoute: ProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiCreateOrderServerRoute: ApiCreateOrderServerRoute,
  ApiDebugProductsServerRoute: ApiDebugProductsServerRoute,
  ApiProductsServerRoute: ApiProductsServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
